config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  # resources :reviews
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :catagory, acceptance: { accept: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render new:, status: :unprocessable_entity

    end

  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update

    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to @restaurant

  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other

  end

private

def restaurant_params
  params.require(:restaurant).permit(:name, :address, :catagory, :phone_number)
end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end


  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:body, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.select :catagory, :collection => ["chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>What changes would you like to make?</h1>
<%= render "form", restaurant: @restaurant %>
 <%= link_to "Home Page", restaurants_path, class: "btn btn-primary" %>

app/views/restaurants/index.html.erb
hello
<ul>
  <%= link_to "Would you like to add a restaurant",  new_restaurant_path, class: "btn btn-primary" %>
  <% @restaurants.each do |rest| %>
    <div class="card-product">
      <div class="card-product-infos">
        <h2><%= rest.name %></h2>
        <li><%= rest.catagory %></li>

        <a class="btn" href=""><%= link_to "See Details", restaurant_path(rest), class: "btn btn-primary"%></a>
        <%# <%= raise %>
      </div>
    </div>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>So there's a new restaurant in town?</h1>

<%= render "form", restaurant: @restaurant %>

<!--
<%= form_with model: @restaurant_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.select :catagory, :collection => ["chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.submit %>
<% end %>
-->
<%= link_to "Home Page", restaurants_path, class: "btn btn-primary" %>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
          <li><%= @restaurant.phone_number %></li>
          <li><%= @restaurant.address %></li>

  <%= link_to "Home Page", restaurants_path, class: "btn btn-primary" %>
  <%= link_to "Edit", edit_restaurant_path, class: "btn btn-primary" %>
  <%= link_to 'Delete',  restaurant_path(@restaurant), class: "btn btn-primary",
    data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
  <br>


  <h2>Would you like to add a review?</h2>
  <%= link_to "Review",  new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
  <br>



  <p><strong>Reviews</strong></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <strong><li class="list-group-item"><%= review.title %></li></strong>
      <li class="list-group-item"><%= review.body %></li>
    <%= link_to "Delete", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary"  %>
    <% end %>
  </ul>

</div>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :title %>

  <%= f.input :body %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>